stages:
  - prerequisites
  - build
  - deploy

variables:
  NAME: flaskproj
  TAG: $NAME:latest
  ENV: test

install_docker_engine:
  stage: prerequisites
  tags: 
    - $ENV
  script:
    - sudo amazon-linux-extras install docker -y
    - sudo systemctl start docker
    - sudo systemctl enable docker
    - sudo usermod -a -G docker gitlab-runner
    - sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose


build_docker_image:
  stage: build
  tags:
    - prod
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/roeidalal/flask-project .
    - docker push registry.gitlab.com/roeidalal/flask-project
  when: manual

deploy_application:
  stage: deploy
  tags:
    - prod
  script:
    - docker-compose up -d
  when: manual