stages:
  - build
  - deploy

variables:
  NAME: flaskproj
  TAG: $NAME:latest
  ENV: prod

build_docker_image:
  stage: build
  tags:
    - prod
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/roeidalal/flask-project .
    - docker push registry.gitlab.com/roeidalal/flask-project
