apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
          - configMapRef:
              name: mongo-configmap
        volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
