kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-053bd02f80b2adb5c
    fsType: ext4

