kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-03357b5f162259964
    fsType: ext4

